# Schema for the configuration files of the govcms_dlm module.

govcms_dlm.settings:
  type: config_object
  label: 'govCMS DLM Email settings'
  mapping:
    suffix:
      type: string
      label: 'DLM marking to apply to e-mails'
